name: CI

on:
  push:
  pull_request_target:
  schedule:
    - cron: "6 20 * * 6"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - truffleruby-head
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Set up Ruby
        run: |
          gem update --system > /dev/null
          gem --version
          gem install -g
      - name: Run tests
        run: rake
