name: CI

on:
  push:
  pull_request_target:
  schedule:
    - cron: "6 20 * * 6"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby:2.5.0
          - ruby:2.5
          - ruby:2.6.0
          - ruby:2.6
          - ruby:2.7.0
          - ruby:2.7
          - jruby:9.2
          - truffleruby-head
        include:
          - ruby: ruby:rc
            continue-on-error: true
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run tests
        run: rake
